[package]
name = "eden"
version = "0.1.0"
authors = ["Claus Matzinger <claus.matzinger+kb@gmail.com>"]

[dependencies]
simple_jwt = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
i2cdev = "*"
clap = "*"
bmp085 = "0.1.1"
ease = "*"
hyper = "*"
log4rs = { version = "*", features = ["serde_yaml"] }
log = "*"
docopt_macros = "*"
chrono = "*"
toml = "*"
mioco = "*"
threadpool = "1.0"
